#
# Makefile
#
# Makefile for pocossh sample
#

include $(POCO_BASE)/build/rules/global

objects = pocossh

target         = pocossh
target_version = 1
target_libs    = PocoSSH PocoFoundation

SYSLIBS += -lssh

include $(POCO_BASE)/build/rules/exec
