//
// MouseEventArgs.h
//
// $Id: //poco/Main/WebWidgets/include/Poco/WebWidgets/MouseEventArgs.h#4 $
//
// Library: WebWidgets
// Package: WebEvents
// Module:  MouseEventArgs
//
// Definition of the MouseEventArgs class.
//
// Copyright (c) 2007, Applied Informatics Software Engineering GmbH.
// and Contributors.
//
// Permission is hereby granted, free of charge, to any person or organization
// obtaining a copy of the software and accompanying documentation covered by
// this license (the "Software") to use, reproduce, display, distribute,
// execute, and transmit the Software, and to prepare derivative works of the
// Software, and to permit third-parties to whom the Software is furnished to
// do so, all subject to the following:
// 
// The copyright notices in the Software and this entire statement, including
// the above license grant, this restriction and the following disclaimer,
// must be included in all copies of the Software, in whole or in part, and
// all derivative works of the Software, unless such copies or derivative
// works are solely in the form of machine-executable object code generated by
// a source language processor.
// 
// THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
// IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
// FITNESS FOR A PARTICULAR PURPOSE, TITLE AND NON-INFRINGEMENT. IN NO EVENT
// SHALL THE COPYRIGHT HOLDERS OR ANYONE DISTRIBUTING THE SOFTWARE BE LIABLE
// FOR ANY DAMAGES OR OTHER LIABILITY, WHETHER IN CONTRACT, TORT OR OTHERWISE,
// ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER
// DEALINGS IN THE SOFTWARE.
//


#ifndef WebWidgets_MouseEventArgs_INCLUDED
#define WebWidgets_MouseEventArgs_INCLUDED


#include "Poco/WebWidgets/WebWidgets.h"


namespace Poco {
namespace WebWidgets {


class Widget;


class WebWidgets_API MouseEventArgs
	/// MouseEventArgs...
{
public:
	MouseEventArgs(Widget* target, int posX, int posY, bool left, bool middle, bool right);
		/// Creates the MouseEventArgs.

	virtual ~MouseEventArgs();
		/// Destroys the MouseEventArgs.

	bool leftButton() const;
		/// Returns if the left mouse button was clicked

	bool rightButton() const;
		/// Returns if the right mouse button was clicked

	bool middleButton() const;
		/// Returns if the middle mouse button was clicked

	int posX() const;
		/// The x position of the mouse pointer relative to the document

	int posY() const;
		/// The y position of the mouse pointer relative to the document

	Widget* target() const;
		/// The element that was clicked

private:
	Widget* _pTarget;
	int     _posX;
	int     _posY;
	bool    _left;
	bool    _middle;
	bool    _right;
};


inline bool MouseEventArgs::leftButton() const
{
	return _left;
}


inline bool MouseEventArgs::rightButton() const
{
	return _right;
}


inline bool MouseEventArgs::middleButton() const
{
	return _middle;
}


inline int MouseEventArgs::posX() const
{
	return _posX;
}


inline int MouseEventArgs::posY() const
{
	return _posY;
}


inline Widget* MouseEventArgs::target() const
{
	return _pTarget;
}


} } // namespace Poco::WebWidgets


#endif // WebWidgets_MouseEventArgs_INCLUDED
