//
// ParserFactory.h
//
// $Id: //poco/Main/WebWidgets/include/Poco/WebWidgets/ParserFactory.h#3 $
//
// Library: WebWidgets
// Package: WebParser
// Module:  ParserFactory
//
// Definition of the ParserFactory class.
//
// Copyright (c) 2007, Applied Informatics Software Engineering GmbH.
// and Contributors.
//
// Permission is hereby granted, free of charge, to any person or organization
// obtaining a copy of the software and accompanying documentation covered by
// this license (the "Software") to use, reproduce, display, distribute,
// execute, and transmit the Software, and to prepare derivative works of the
// Software, and to permit third-parties to whom the Software is furnished to
// do so, all subject to the following:
// 
// The copyright notices in the Software and this entire statement, including
// the above license grant, this restriction and the following disclaimer,
// must be included in all copies of the Software, in whole or in part, and
// all derivative works of the Software, unless such copies or derivative
// works are solely in the form of machine-executable object code generated by
// a source language processor.
// 
// THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
// IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
// FITNESS FOR A PARTICULAR PURPOSE, TITLE AND NON-INFRINGEMENT. IN NO EVENT
// SHALL THE COPYRIGHT HOLDERS OR ANYONE DISTRIBUTING THE SOFTWARE BE LIABLE
// FOR ANY DAMAGES OR OTHER LIABILITY, WHETHER IN CONTRACT, TORT OR OTHERWISE,
// ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER
// DEALINGS IN THE SOFTWARE.
//


#ifndef WebWidgets_ParserFactory_INCLUDED
#define WebWidgets_ParserFactory_INCLUDED


#include "Poco/WebWidgets/WebWidgets.h"
#include "Poco/WebWidgets/Widget.h"
#include "Poco/WebWidgets/XMLUtil.h"
#include "Poco/AutoPtr.h"


namespace Poco {
namespace XML {
	class Element;
}
}


namespace Poco {
namespace WebWidgets {


class WebWidgets_API ParserFactory
	/// ParserFactory creates a widget of a given type from an XML document
{
public:
	ParserFactory();
		/// Creates the ParserFactory.

	virtual ~ParserFactory();
		/// Destroys the ParserFactory.

	virtual Poco::AutoPtr<Widget> load(const Poco::XML::Element* pElem) const = 0;
		/// Loads a Widget from the given XML element
};


template <typename T>
class ParserFactoryImpl: public ParserFactory
	/// ParserFactoryImpl acts as a template for fast ParserFactory creation
{
public:
	ParserFactoryImpl()
		/// Creates the ParserFactory.
	{
	}

	~ParserFactoryImpl()
		/// Destroys the ParserFactory.
	{
	}

	Poco::AutoPtr<Widget> load(const Poco::XML::Element* pElem) const
	{
		Poco::AutoPtr<Widget> ptrWidget = Poco::AutoPtr<Widget>(new T(pElem));
		
		return ptrWidget;
	}

};


} } // namespace Poco::WebWidgets


#endif // WebWidgets_ParserFactory_INCLUDED
