#
# Makefile
#
# $Id: //poco/Main/PageCompiler/Makefile#1 $
#
# Makefile for Poco C++ Server Page Compiler
#

include $(POCO_BASE)/build/rules/global

objects = Page PageCompiler

target         = cpspc
target_version = 1
target_libs    = PocoNet PocoUtil PocoXML PocoFoundation

include $(POCO_BASE)/build/rules/exec
