#
# Makefile
#
# $Id: //poco/Main/Foundation/samples/inflate/Makefile#5 $
#
# Makefile for Poco inflate
#

include $(POCO_BASE)/build/rules/global

objects = inflate

target         = inflate
target_version = 1
target_libs    = PocoFoundation

include $(POCO_BASE)/build/rules/exec
