#
# Makefile
#
# Makefile for Poco SQL RowFormatter sample
#

include $(POCO_BASE)/build/rules/global

objects = RowFormatter

target         = RowFormatter
target_version = 1
target_libs    = PocoSQLSQLite PocoSQL PocoFoundation

include $(POCO_BASE)/build/rules/exec
