#
# Makefile
#
# Makefile for Poco SSH Library
#

include $(POCO_BASE)/build/rules/global

SYSLIBS += -lssh

objects = SSHChannelStream SSHClient SSHException SSHHostKeyManager SSHServer SSHSession

target         = PocoSSH
target_version = 1
target_libs    = PocoFoundation

include $(POCO_BASE)/build/rules/lib
