if(@POCO_UNBUNDLED_PCRE@)
	include(CMakeFindDependencyMacro)
	list(APPEND CMAKE_MODULE_PATH "${CMAKE_CURRENT_LIST_DIR}")
	find_dependency(PCRE2 REQUIRED)
endif()
if(@POCO_UNBUNDLED_ZLIB@)
	include(CMakeFindDependencyMacro)
	list(APPEND CMAKE_MODULE_PATH "${CMAKE_CURRENT_LIST_DIR}")
	find_dependency(ZLIB REQUIRED)
endif()

include("${CMAKE_CURRENT_LIST_DIR}/PocoFoundationTargets.cmake")
