#
# Makefile
#
# $Id: //poco/1.4/Data/samples/Makefile#1 $
#
# Makefile for Poco Data Samples
#

.PHONY: projects
clean all: projects
projects:
	$(MAKE) -C Binding $(MAKECMDGOALS)
	$(MAKE) -C TypeHandler $(MAKECMDGOALS)
	$(MAKE) -C RecordSet $(MAKECMDGOALS)
	$(MAKE) -C Tuple $(MAKECMDGOALS)
