#
# Makefile
#
# $Id: //poco/1.4/Shell/Makefile#1 $
#
# Makefile for Poco Shell Library
#

include $(POCO_BASE)/build/rules/global

objects = AbstractCommand Command CommandFactory CommandProcessor \
	HelpCommand HelpCommandFactory LoginCommand LoginCommandFactory \
	QuitCommand QuitCommandFactory ResponseStream \
	Session Connection ConnectionFactory

target         = PocoShell
target_version = 2
target_libs    = PocoUtil PocoNet PocoXML PocoFoundation

include $(POCO_BASE)/build/rules/lib
