#
# Makefile
#
# Makefile for Poco PDF Template sample
#

include $(POCO_BASE)/build/rules/global

objects = Template

target         = Template
target_version = 1
target_libs    = PocoPDF PocoUtil PocoXML PocoFoundation

include $(POCO_BASE)/build/rules/exec
