#
# Makefile
#
# Makefile for RemotingNG PizzeriaClientWS sample.
#

include $(POCO_BASE)/build/rules/global

objects = \
	DeliveryAddress \
	DeliveryAddressDetails \
	ExtTopping \
	GetAnyPizzaReply \
	GetAnyPizzaRequest \
	GetMostPopularToppingReply \
	GetMostPopularToppingRequest \
	GetPizzaNamesReply \
	GetPizzaNamesRequest \
	GetPizzasReply \
	GetPizzasRequest \
	GetToppingsReply \
	GetToppingsRequest \
	GetWaitTimeReply \
	GetWaitTimeRequest \
	IPizzaDeliveryService \
	OrderReply \
	OrderRequest \
	Pizza \
	PizzaDeliveryService \
	PizzaDeliveryService12 \
	PizzaDeliveryServiceClientHelper \
	PizzaDeliveryServiceProxy \
	PizzaDeliveryServiceProxyFactory \
	PizzaDetails \
	Topping \
	PizzeriaClient

target         = PizzeriaClient
target_version = 1
target_libs    = PocoRemotingNGSOAP PocoRemotingNG PocoUtil PocoNet PocoXML PocoFoundation

include $(POCO_BASE)/build/rules/exec
