#
# Makefile
#
# $Id: //poco/1.4/NetEx/samples/Makefile#2 $
#
# Makefile for Poco NetEx Samples
#

.PHONY: projects
clean all: projects
projects:
	$(MAKE) -C Ping $(MAKECMDGOALS)
	$(MAKE) -C SNMP $(MAKECMDGOALS)
