#
# Makefile
#
# $Id$
#
# Makefile for Poco JSON BenchmarkApp
#

include $(POCO_BASE)/build/rules/global

objects = BenchmarkApp

target         = BenchmarkApp
target_version = 1
target_libs    = PocoJSON PocoFoundation

include $(POCO_BASE)/build/rules/exec
