#
# Makefile
#
# Makefile for Poco dict
#

include $(POCO_BASE)/build/rules/global

objects = dict

target         = dict
target_version = 1
target_libs    = PocoUtil PocoNet PocoXML PocoJSON PocoFoundation

include $(POCO_BASE)/build/rules/exec
