#
# Makefile
#
# Makefile for Poco base64encode
#

include $(POCO_BASE)/build/rules/global

objects = base64encode

target         = base64encode
target_version = 1
target_libs    = PocoFoundation

include $(POCO_BASE)/build/rules/exec
