#
# Makefile
#
# $Id: //poco/Main/WebWidgets/ExtJS/samples/Server/Makefile#1 $
#
# Makefile for Poco Server
#

include $(POCO_BASE)/build/rules/global

objects = Server

target         = Server
target_version = 1
target_libs    = PocoExtJS PocoWebWidgets PocoFoundation PocoXML PocoNet PocoUtil

include $(POCO_BASE)/build/rules/exec
