#
# Makefile
#
# Makefile for ConvertTemperature sample
#

include $(POCO_BASE)/build/rules/global

objects = \
	ConvertTemp \
	ConvertTempResponse \
	ConvertTemperature \
	ConvertTemperatureClient \
	ConvertTemperatureClientHelper \
	ConvertTemperatureProxy \
	ConvertTemperatureProxyFactory \
	IConvertTemperature

target         = ConvertTemperature
target_version = 1
target_libs    = PocoRemotingNGSOAP PocoRemotingNG PocoUtil PocoNet PocoXML PocoFoundation

include $(POCO_BASE)/build/rules/exec
