#
# Makefile
#
# Makefile for RemotingNG TimeServer sample
#

include $(POCO_BASE)/build/rules/global

objects = TimeServer ITimeService TimeService TimeServiceRemoteObject TimeServiceServerHelper TimeServiceSkeleton

target         = TimeServer
target_version = 1
target_libs    = PocoRemotingNGSOAP PocoRemotingNG PocoUtil PocoNet PocoXML PocoFoundation

include $(POCO_BASE)/build/rules/exec
