#
# Makefile
#
# $Id: //poco/1.1.0/Net/samples/HTTPTimeServer/Makefile#1 $
#
# Makefile for Poco HTTPTimeServer
#

include $(POCO_BASE)/build/rules/global

objects = HTTPTimeServer

target         = HTTPTimeServer
target_version = 1
target_libs    = PocoFoundation PocoXML PocoNet PocoUtil

include $(POCO_BASE)/build/rules/exec
