#
# Makefile
#
# $Id: //poco/Main/Net/samples/HTTPTimeServer/Makefile#2 $
#
# Makefile for Poco HTTPTimeServer
#

include $(POCO_BASE)/build/rules/global

objects = HTTPTimeServer

target         = HTTPTimeServer
target_version = 1
target_libs    = PocoUtil PocoNet PocoXML PocoFoundation

include $(POCO_BASE)/build/rules/exec
