#
# Makefile
#
# $Id$
#
# Makefile for Poco Redis testsuite
#

include $(POCO_BASE)/build/rules/global

objects = Driver RedisTest RedisTestSuite

target         = testrunner
target_version = 1
target_libs    = PocoRedis PocoFoundation PocoNet CppUnit

include $(POCO_BASE)/build/rules/exec
