#
# Makefile
#
# $Id: //poco/Main/Zip/samples/Makefile#1 $
#
# Makefile for Poco Util Samples
#

.PHONY: projects
clean all: projects
projects:
	$(MAKE) -C unzip $(MAKECMDGOALS)
	$(MAKE) -C zip $(MAKECMDGOALS)
