#
# Makefile
#
# Makefile for Poco PDF Samples
#

.PHONY: projects
clean all: projects
projects:
	$(MAKE) -C Text $(MAKECMDGOALS)
	$(MAKE) -C Image $(MAKECMDGOALS)
	$(MAKE) -C Template $(MAKECMDGOALS)
