#
# Makefile
#
# Makefile for Poco tcpclient
#

include $(POCO_BASE)/build/rules/global

objects = tcpclient

target         = tcpclient
target_version = 1
target_libs    = PocoNet PocoFoundation

include $(POCO_BASE)/build/rules/exec
