#
# Makefile
#
# $Id: //poco/svn/NetSSL_OpenSSL/samples/Makefile#1 $
#
# Makefile for Poco NetSSL Samples
#

.DEFAULT all:
	$(MAKE) -C HTTPSTimeServer $(MAKECMDGOALS)
	$(MAKE) -C download $(MAKECMDGOALS)
