#
# Makefile
#
# Makefile for Poco NetSSL Samples
#

.DEFAULT all:
	$(MAKE) -C HTTPSTimeServer $(MAKECMDGOALS)
	$(MAKE) -C download $(MAKECMDGOALS)
	$(MAKE) -C Mail $(MAKECMDGOALS)
	$(MAKE) -C TwitterClient $(MAKECMDGOALS)
	$(MAKE) -C SetSourceIp $(MAKECMDGOALS)
