#
# Makefile
#
# Makefile for Poco XSDParser testsuite
#

include $(POCO_BASE)/build/rules/global

objects = XSDParserTestSuite Driver \
	XSDParserTest

target         = testrunner
target_version = 1
target_libs    = PocoXSDParser PocoXSDTypes PocoXML PocoFoundation CppUnit

include $(POCO_BASE)/build/rules/exec
