#
# Makefile
#
# Makefile for Poco SQL WebNotifier sample
#

include $(POCO_BASE)/build/rules/global

objects = WebNotifier

target         = WebNotifier
target_version = 1
target_libs    = PocoSQLSQLite PocoSQL PocoNet PocoFoundation

include $(POCO_BASE)/build/rules/exec
