#
# Makefile
#
# $Id: //poco/svn/Util/samples/SampleApp/Makefile#1 $
#
# Makefile for Poco SampleApp
#

include $(POCO_BASE)/build/rules/global

objects = SampleApp

target         = SampleApp
target_version = 1
target_libs    = PocoUtil PocoXML PocoFoundation

include $(POCO_BASE)/build/rules/exec
