#
# Makefile
#
# $Id: //poco/1.1.0/Util/samples/SampleApp/Makefile#1 $
#
# Makefile for Poco SampleApp
#

include $(POCO_BASE)/build/rules/global

objects = SampleApp

target         = SampleApp
target_version = 1
target_libs    = PocoFoundation PocoXML PocoUtil

include $(POCO_BASE)/build/rules/exec
