#
# Makefile
#
# Makefile for Poco PDF Image sample
#

include $(POCO_BASE)/build/rules/global

objects = Image

target         = Image
target_version = 1
target_libs    = PocoPDF PocoFoundation

include $(POCO_BASE)/build/rules/exec
