#
# Makefile
#
# $Id: //poco/1.3/Data/samples/TypeHandler/Makefile#1 $
#
# Makefile for Poco Data TypeHandler sample
#

include $(POCO_BASE)/build/rules/global

objects = TypeHandler

target         = TypeHandler
target_version = 1
target_libs    = PocoFoundation PocoData PocoSQLite

include $(POCO_BASE)/build/rules/exec
