#
# Makefile
#
# Makefile for MCPServer
#

include $(POCO_BASE)/build/rules/global

objects = MCPServer

target         = MCPServer
target_version = $(LIBVERSION)
target_libs    = PocoAIMCP PocoUtil PocoXML PocoJSON PocoFoundation

include $(POCO_BASE)/build/rules/exec
