#
# Makefile
#
# $Id: //poco/1.4/ApacheConnector/samples/Makefile#1 $
#
# Makefile for Poco ApacheConnector Samples
#

.PHONY: projects
clean all: projects
projects:
	$(MAKE) -C TimeServer $(MAKECMDGOALS)
	$(MAKE) -C FormServer $(MAKECMDGOALS)
