#
# Makefile
#
# $Id: //poco/svn/Util/samples/Makefile#1 $
#
# Makefile for Poco Util Samples
#

.PHONY: projects
clean all: projects
projects:
	$(MAKE) -C SampleApp $(MAKECMDGOALS)
	$(MAKE) -C SampleServer $(MAKECMDGOALS)
	$(MAKE) -C Units $(MAKECMDGOALS)
