#
# Makefile
#
# Makefile for Poco XML Samples
#

.PHONY: projects
clean distclean all: projects
projects:
	$(MAKE) -C DOMParser $(MAKECMDGOALS)
	$(MAKE) -C DOMWriter $(MAKECMDGOALS)
	$(MAKE) -C PrettyPrint $(MAKECMDGOALS)
	$(MAKE) -C SAXParser $(MAKECMDGOALS)
