#
# Makefile
#
# $Id: //poco/1.1.0/XML/samples/Makefile#1 $
#
# Makefile for Poco XML Samples
#

.DEFAULT all:
	$(MAKE) -C DOMParser $(MAKECMDGOALS)
	$(MAKE) -C DOMWriter $(MAKECMDGOALS)
	$(MAKE) -C PrettyPrint $(MAKECMDGOALS)
	$(MAKE) -C SAXParser $(MAKECMDGOALS)
