#
# Makefile
#
# Makefile for Poco XSDTypes testsuite
#

include $(POCO_BASE)/build/rules/global

objects = XSDTypesTestSuite Driver \
	XSDTypesTest

target         = testrunner
target_version = 1
target_libs    = PocoXSDTypes PocoFoundation CppUnit

include $(POCO_BASE)/build/rules/exec
