#
# Makefile
#
# $Id$
#
# Makefile for Poco ASN
#

include $(POCO_BASE)/build/rules/global

INCLUDE += -I $(POCO_BASE)/ASN/include/Poco/ASN

objects = ASN1 ASN1Codec ASN1FactoryDefault ASN1Types

target         = PocoASN
target_version = $(LIBVERSION)
target_libs    = PocoFoundation

include $(POCO_BASE)/build/rules/lib
