#
# Makefile
#
# Makefile for Poco AI MCP HTTP testsuite
#

include $(POCO_BASE)/build/rules/global

objects = Driver HTTPTestSuite HTTPTest

target         = testrunner
target_version = 1
target_libs    = PocoAIMCPHTTP PocoAIMCP PocoNet PocoJSON PocoFoundation CppUnit

include $(POCO_BASE)/build/rules/exec
