#
# Makefile
#
# Makefile for Poco SQL Binding sample
#

include $(POCO_BASE)/build/rules/global

objects = Binding

target         = Binding
target_version = 1
target_libs    = PocoSQLSQLite PocoSQL PocoFoundation

include $(POCO_BASE)/build/rules/exec
