include(CMakeFindDependencyMacro)
find_dependency(PocoFoundation)
find_dependency(PocoXML)
find_dependency(PocoNet)
find_dependency(PocoRemotingNG)
include("${CMAKE_CURRENT_LIST_DIR}/PocoRemotingNGSOAPTargets.cmake")
