#
# Makefile
#
# $Id: //poco/1.1.0/Net/samples/Mail/Makefile#1 $
#
# Makefile for Poco Mail
#

include $(POCO_BASE)/build/rules/global

objects = Mail

target         = Mail
target_version = 1
target_libs    = PocoFoundation PocoXML PocoNet PocoUtil

include $(POCO_BASE)/build/rules/exec
