#
# Makefile
#
# Makefile for Poco Mail
#

include $(POCO_BASE)/build/rules/global

objects = Mail

target         = Mail
target_version = 1
target_libs    = PocoUtil PocoNet PocoXML PocoJSON PocoFoundation

include $(POCO_BASE)/build/rules/exec
