#
# Makefile
#
# $Id: //poco/Main/WebWidgets/testsuite/Makefile#4 $
#
# Makefile for Poco WebWidgets testsuite
#

include $(POCO_BASE)/build/rules/global

objects = WebWidgetsTestSuite Driver \
	WebWidgetsTest

target         = testrunner
target_version = 1
target_libs    = PocoWebWidgets PocoNet PocoFoundation CppUnit

include $(POCO_BASE)/build/rules/exec
