#
# Makefile
#
# $Id: //poco/Main/Zip/samples/zip/Makefile#1 $
#
# Makefile for Poco SampleApp
#

include $(POCO_BASE)/build/rules/global

objects = zip

target         = zip
target_version = 1
target_libs    = PocoZip PocoUtil PocoXML PocoFoundation

include $(POCO_BASE)/build/rules/exec
