#
# Makefile
#
# $Id: //poco/1.4/ApacheConnector/samples/TimeServer/Makefile#1 $
#
# Makefile for Poco ApacheConnector sample
#

include $(POCO_BASE)/build/rules/global

objects = TimeServer

target         = TimeServer
target_version = 1
target_libs    = PocoFoundation PocoNet

include $(POCO_BASE)/build/rules/dylib
