#
# Makefile
#
# Makefile for Poco SQL Tuple sample
#

include $(POCO_BASE)/build/rules/global

objects = Tuple

target         = Tuple
target_version = 1
target_libs    = PocoSQLSQLite PocoSQL PocoFoundation

include $(POCO_BASE)/build/rules/exec
