#
# Makefile
#
# $Id: //poco/Main/Foundation/samples/Logger/Makefile#5 $
#
# Makefile for Poco Logger
#

include $(POCO_BASE)/build/rules/global

objects = Logger

target         = Logger
target_version = 1
target_libs    = PocoFoundation

include $(POCO_BASE)/build/rules/exec
