#
# Makefile
#
# Makefile for Poco Modules testsuite
#

include $(POCO_BASE)/build/rules/global

objects = ModulesTestSuite Driver ModulesTest

target         = testrunner
target_version = 1
target_libs    = PocoModules PocoFoundation CppUnit

include $(POCO_BASE)/build/rules/exec
