#
# Makefile
#
# $Id$
#
# Makefile for Poco JSON ASN1EncodeDecode
#

include $(POCO_BASE)/build/rules/global

objects = ASN1EncodeDecode

target         = ASN1EncodeDecode
target_version = 1
target_libs    = PocoASN PocoFoundation

include $(POCO_BASE)/build/rules/exec
