#
# Makefile
#
# Makefile for Poco TextEncodingCompiler
#

include $(POCO_BASE)/build/rules/global

objects = TextEncodingCompiler

target         = tec
target_version = 1
target_libs    = PocoUtil PocoNet PocoXML PocoJSON PocoFoundation

include $(POCO_BASE)/build/rules/exec
