#
# Makefile
#
# $Id: //poco/1.3/XML/samples/DOMParser/Makefile#2 $
#
# Makefile for Poco DOMParser
#

include $(POCO_BASE)/build/rules/global

objects = DOMParser

target         = DOMParser
target_version = 1
target_libs    = PocoXML PocoFoundation

include $(POCO_BASE)/build/rules/exec
