#
# Makefile
#
# $Id: //poco/1.1.0/Util/samples/SampleServer/Makefile#1 $
#
# Makefile for Poco SampleServer
#

include $(POCO_BASE)/build/rules/global

objects = SampleServer

target         = SampleServer
target_version = 1
target_libs    = PocoFoundation PocoXML PocoUtil

include $(POCO_BASE)/build/rules/exec
