#
# Makefile
#
# $Id: //poco/Main/Util/samples/SampleServer/Makefile#3 $
#
# Makefile for Poco SampleServer
#

include $(POCO_BASE)/build/rules/global

objects = SampleServer

target         = SampleServer
target_version = 1
target_libs    = PocoUtil PocoXML PocoFoundation

include $(POCO_BASE)/build/rules/exec
