#
# Makefile
#
# Makefile for Poco DateTime
#

include $(POCO_BASE)/build/rules/global

objects = DateTime

target         = DateTime
target_version = 1
target_libs    = PocoFoundation

include $(POCO_BASE)/build/rules/exec
