#
# Makefile
#
# $Id: //poco/1.4/Foundation/samples/LogRotation/Makefile#1 $
#
# Makefile for Poco LogRotation
#

include $(POCO_BASE)/build/rules/global

objects = LogRotation

target         = LogRotation
target_version = 1
target_libs    = PocoFoundation

include $(POCO_BASE)/build/rules/exec
