#
# Makefile
#
# Makefile for Poco Data RowFormatter sample
#

include $(POCO_BASE)/build/rules/global

objects = RowFormatter

target         = RowFormatter
target_version = 1
target_libs    = PocoDataSQLite PocoData PocoFoundation

include $(POCO_BASE)/build/rules/exec
