if(ENABLE_REMOTINGNG_TCP)
	add_subdirectory(TimeServerTCP)
	add_subdirectory(TimeClientTCP)
	if(UNIX)
		add_subdirectory(TimeServerUDS)
		add_subdirectory(TimeClientUDS)
	endif()
endif()

if(ENABLE_REMOTINGNG_REST)
	add_subdirectory(PizzeriaREST)
	add_subdirectory(PizzeriaClientREST)
	if(ENABLE_NETSSL)
		add_subdirectory(TwilioSMS)
	endif()
endif()

if(ENABLE_REMOTINGNG_SOAP)
	add_subdirectory(CheckVat)
	add_subdirectory(ConvertTemperature)
	add_subdirectory(Weather)
	add_subdirectory(TimeServer)
	add_subdirectory(TimeClient)
	add_subdirectory(Pizzeria)
	add_subdirectory(PizzeriaClient)
	add_subdirectory(PizzeriaClientWS)
	add_subdirectory(ONVIF)
	add_subdirectory(ONVIFClient)
endif()
