#
# Makefile
#
# Makefile for Poco RemotingNG Samples
#

.DEFAULT all:
	$(MAKE) -C CheckVat $(MAKECMDGOALS)
	$(MAKE) -C ConvertTemperature $(MAKECMDGOALS)
	$(MAKE) -C Weather $(MAKECMDGOALS)
	$(MAKE) -C TimeServer $(MAKECMDGOALS)
	$(MAKE) -C TimeClient $(MAKECMDGOALS)
	$(MAKE) -C Pizzeria $(MAKECMDGOALS)
	$(MAKE) -C PizzeriaClient $(MAKECMDGOALS)
	$(MAKE) -C PizzeriaClientWS $(MAKECMDGOALS)
	$(MAKE) -C TimeServerTCP $(MAKECMDGOALS)
	$(MAKE) -C TimeClientTCP $(MAKECMDGOALS)
	$(MAKE) -C TimeServerUDS $(MAKECMDGOALS)
	$(MAKE) -C TimeClientUDS $(MAKECMDGOALS)
	$(MAKE) -C PizzeriaREST $(MAKECMDGOALS)
	$(MAKE) -C PizzeriaClientREST $(MAKECMDGOALS)
	$(MAKE) -C TwilioSMS $(MAKECMDGOALS)
	$(MAKE) -C ONVIF $(MAKECMDGOALS)
	$(MAKE) -C ONVIFClient $(MAKECMDGOALS)
