#
# Makefile
#
# Makefile for Poco SQL RecordSet sample
#

include $(POCO_BASE)/build/rules/global

objects = RecordSet

target         = RecordSet
target_version = 1
target_libs    = PocoSQLSQLite PocoSQL PocoFoundation

include $(POCO_BASE)/build/rules/exec
