#
# Makefile
#
# $Id: //poco/Main/template/library.make#3 $
#
# Makefile for Poco ExtJS
#

include $(POCO_BASE)/build/rules/global

objects = <SourceFilesHere>

target         = PocoExtJS
target_version = $(LIBVERSION)
target_libs    = PocoFoundation

include $(POCO_BASE)/build/rules/lib
