#
# Makefile
#
# $Id: //poco/Main/template/library.make#3 $
#
# Makefile for Poco ExtJS
#

include $(POCO_BASE)/build/rules/global

objects = AbstractTableCellHandler ArrayTableSerializer \
	ButtonCellRenderer CellInitializer CellRenderer \
	CheckButtonCellRenderer CollapsibleRenderer \
	ComboBoxCellRenderer DateFieldCellRenderer \
	FormRenderer FrameRenderer GridLayoutRenderer \
	HorizontalLayoutRenderer HTMLRenderer \
	ImageButtonCellRenderer ImageRenderer \
	LabelRenderer LayoutRenderer ListBoxCellRenderer \
	NumberFieldCellRenderer PageRenderer PanelRenderer \
	PasswordFieldCellRenderer ProgressIndicatorRenderer \
	RadioButtonCellRenderer SubmitButtonCellRenderer \
	TableCellHandlerFactory TableRenderer TabViewRenderer \
	TextEditCellRenderer TextFieldCellRenderer \
	TimeFieldCellRenderer ToggleButtonCellRenderer \
	Utility VerticalLayoutRenderer 

target         = PocoExtJS
target_version = $(LIBVERSION)
target_libs    = PocoWebWidgets PocoNet PocoUtil PocoXML PocoFoundation

include $(POCO_BASE)/build/rules/lib
