#
# Makefile
#
# $Id: //poco/Main/WebWidgets/ExtJS/samples/Server/Makefile#1 $
#
# Makefile for Poco Server
#

include $(POCO_BASE)/build/rules/global

objects = Picross PicrossFrame PicrossPage RAWReader

target         = picross
target_version = 1
target_libs    = PocoExtJS PocoWebWidgets PocoUtil PocoNet PocoXML PocoFoundation

include $(POCO_BASE)/build/rules/exec
