include(CMakeFindDependencyMacro)
set(CMAKE_PREFIX_PATH ${CMAKE_CURRENT_LIST_DIR})
find_dependency(PocoFoundation)
find_dependency(PocoNet)
find_dependency(PocoASN)
include("${CMAKE_CURRENT_LIST_DIR}/PocoNetExTargets.cmake")