#
# Makefile
#
# $Id: //poco/Main/Foundation/samples/dir/Makefile#5 $
#
# Makefile for Poco dir
#

include $(POCO_BASE)/build/rules/global

objects = dir

target         = dir
target_version = 1
target_libs    = PocoFoundation

include $(POCO_BASE)/build/rules/exec
