#
# Makefile
#
# Makefile for MetricsSample
#

include $(POCO_BASE)/build/rules/global

objects = MetricsSample

target         = MetricsSample
target_version = $(LIBVERSION)
target_libs    = PocoPrometheus PocoNet PocoUtil PocoXML PocoJSON PocoFoundation

include $(POCO_BASE)/build/rules/exec
