#
# Makefile
#
# $Id: //poco/1.7/DNSSD/samples/Makefile#1 $
#
# Makefile for DNSSD Samples
#

.PHONY: projects
clean all: projects
projects:
	$(MAKE) -C DNSSDBrowser $(MAKECMDGOALS)
	$(MAKE) -C HTTPTimeServer $(MAKECMDGOALS)
