#
# Makefile
#
# $Id: //poco/Main/PDF/samples/Text/Makefile#1 $
#
# Makefile for Poco PDF Text sample
#

include $(POCO_BASE)/build/rules/global

objects = Text

target         = Text
target_version = 1
target_libs    = PocoPDF PocoFoundation

include $(POCO_BASE)/build/rules/exec
