#
# Makefile
#
# Makefile for Poco ActiveRecord Compiler
#

include $(POCO_BASE)/build/rules/global

objects = Parser CodeGenerator HeaderGenerator ImplGenerator Compiler

target         = poco-arc
target_libs    = PocoUtil PocoJSON PocoXML PocoFoundation

include $(POCO_BASE)/build/rules/exec
