#
# Makefile
#
# $Id: //poco/1.2/Net/samples/Ping/Makefile#3 $
#
# Makefile for Poco ping
#

include $(POCO_BASE)/build/rules/global

objects = Ping

target         = Ping
target_version = 1
target_libs    = PocoUtil PocoNet PocoXML PocoFoundation

include $(POCO_BASE)/build/rules/exec
