#
# Makefile
#
# $Id: //poco/Main/PDF/testsuite/Makefile#7 $
#
# Makefile for Poco PDF testsuite
#

include $(POCO_BASE)/build/rules/global

objects = PDFTestSuite Driver PDFTest

target         = testrunner
target_version = 1
target_libs    = PocoPDF PocoFoundation PocoCppUnit

include $(POCO_BASE)/build/rules/exec
