#
# Makefile
#
# Makefile for Poco PDF testsuite
#

include $(POCO_BASE)/build/rules/global

objects = PDFTestSuite Driver PDFTest

target         = testrunner
target_version = 1
target_libs    = PocoPDF PocoFoundation CppUnit

include $(POCO_BASE)/build/rules/exec
