#
# Makefile
#
# $Id: //poco/Main/Net/samples/httpget/Makefile#2 $
#
# Makefile for Poco httpget
#

include $(POCO_BASE)/build/rules/global

objects = httpget

target         = httpget
target_version = 1
target_libs    = PocoUtil PocoNet PocoXML PocoFoundation

include $(POCO_BASE)/build/rules/exec
