#
# Makefile
#
# Makefile for Poco AI MCP (Model Context Protocol core and stdio transport)
#

include $(POCO_BASE)/build/rules/global

objects = Message Content Dispatcher Server Client StdIOServer

target         = PocoAIMCP
target_version = $(LIBVERSION)
target_libs    = PocoJSON PocoFoundation

include $(POCO_BASE)/build/rules/lib
