#
# Makefile
#
# $Id: //poco/Main/template/sample.make#4 $
#
# Makefile for Poco interfaces
#

include $(POCO_BASE)/build/rules/global

objects = interfaces

target         = interfaces
target_version = 1
target_libs    = PocoUtil PocoNet PocoFoundation

include $(POCO_BASE)/build/rules/exec
