# This is a sample configuration file.
logging.loggers.root.channel = c1
logging.loggers.root.level = debug
logging.formatters.f1.class = PatternFormatter
logging.formatters.f1.pattern = [%p] %t
logging.channels.c1.class = ConsoleChannel
logging.channels.c1.formatter = f1
