#
# Makefile
#
# $Id$
#
# Makefile for Poco ASN testsuite
#

include $(POCO_BASE)/build/rules/global

objects = Driver ASN1Test ASNTestSuite

target         = testrunner
target_version = 1
target_libs    = PocoASN PocoFoundation CppUnit

include $(POCO_BASE)/build/rules/exec
