#
# Makefile
#
# Makefile for Poco SQL TypeHandler sample
#

include $(POCO_BASE)/build/rules/global

objects = TypeHandler

target         = TypeHandler
target_version = 1
target_libs    = PocoSQLSQLite PocoSQL PocoFoundation

include $(POCO_BASE)/build/rules/exec
