#
# Makefile
#
# $Id: //poco/1.1.0/Net/samples/EchoServer/Makefile#1 $
#
# Makefile for Poco EchoServer
#

include $(POCO_BASE)/build/rules/global

objects = EchoServer

target         = EchoServer
target_version = 1
target_libs    = PocoFoundation PocoXML PocoNet PocoUtil

include $(POCO_BASE)/build/rules/exec
