#
# Makefile
#
# $Id: //poco/Main/Net/samples/EchoServer/Makefile#2 $
#
# Makefile for Poco EchoServer
#

include $(POCO_BASE)/build/rules/global

objects = EchoServer

target         = EchoServer
target_version = 1
target_libs    = PocoUtil PocoNet PocoXML PocoFoundation

include $(POCO_BASE)/build/rules/exec
