#
# Makefile
#
# Makefile for Poco CppParser testsuite
#

include $(POCO_BASE)/build/rules/global

objects = CppParserTestSuite Driver \
	CppParserTest \
	AttributesTestSuite AttributesParserTest

target         = testrunner
target_version = 1
target_libs    = PocoCppParser PocoFoundation CppUnit

include $(POCO_BASE)/build/rules/exec
