include(CMakeFindDependencyMacro)
find_dependency(PocoFoundation)
find_dependency(PocoUtil)
find_dependency(PocoNet)
find_dependency(OpenSSL REQUIRED COMPONENTS SSL)
include("${CMAKE_CURRENT_LIST_DIR}/PocoNetSSLWinTargets.cmake")
