include(CMakeFindDependencyMacro)
find_dependency(PocoFoundation)
set(ENABLE_XML @ENABLE_XML@)
if(ENABLE_XML)
    find_dependency(PocoXML)
endif(ENABLE_XML)
set(ENABLE_JSON @ENABLE_JSON@)
if(ENABLE_JSON)
    find_dependency(PocoJSON)
endif(ENABLE_JSON)
include("${CMAKE_CURRENT_LIST_DIR}/PocoUtilTargets.cmake")
