#
# Makefile
#
# $Id: //poco/Main/template/sample.make#4 $
#
# Makefile for Poco genrsakey
#

include $(POCO_BASE)/build/rules/global

objects = genrsakey

target         = genrsakey
target_version = 1
target_libs    = PocoCrypto PocoUtil PocoXML PocoFoundation

include $(POCO_BASE)/build/rules/exec
