#
# Makefile
#
# Makefile for Poco Data testsuite library
#

include $(POCO_BASE)/build/rules/global

objects = SQLExecutor

target          = PocoDataTest
target_version  = 1
target_libs     = PocoData PocoFoundation CppUnit
target_includes = $(POCO_BASE)/Data/SQLParser $(POCO_BASE)/Data/SQLParser/src $(POCO_BASE)/Data/DataTest/include

include $(POCO_BASE)/build/rules/lib
