#
# Makefile
#
# Makefile for Poco XSDParser
#

include $(POCO_BASE)/build/rules/global

objects = Constants StateMachine Utility XSDContentHandler

target         = PocoXSDParser
target_version = $(LIBVERSION)
target_libs    = PocoXSDTypes PocoXML PocoFoundation

include $(POCO_BASE)/build/rules/lib
