#
# Makefile
#
# Makefile for Poco AI MCP HTTP (Streamable HTTP client transport)
#

include $(POCO_BASE)/build/rules/global

objects = SessionFactory HTTPClient

target         = PocoAIMCPHTTP
target_version = $(LIBVERSION)
target_libs    = PocoAIMCP PocoNet PocoJSON PocoFoundation

include $(POCO_BASE)/build/rules/lib
