#
# Makefile
#
# $Id: //poco/Main/Data/samples/Tuple/Makefile#1 $
#
# Makefile for Poco Data Tuple sample
#

include $(POCO_BASE)/build/rules/global

objects = Binding

target         = Tuple
target_version = 1
target_libs    = PocoFoundation PocoData PocoSQLite

include $(POCO_BASE)/build/rules/exec
