#
# Makefile
#
# Makefile for ONVIF
#

include $(POCO_BASE)/build/rules/global

objects := Amalgamated

target         = ONVIF
target_includes = ../include
target_version = 1
target_libs    = PocoFoundation

include $(POCO_BASE)/build/rules/lib
