#
# Makefile
#
# Makefile for Poco ActiveMethod
#

include $(POCO_BASE)/build/rules/global

objects = ActiveMethod

target         = ActiveMethod
target_version = 1
target_libs    = PocoFoundation

include $(POCO_BASE)/build/rules/exec
