#
# Makefile
#
# $Id: //poco/Main/Foundation/samples/ActiveMethod/Makefile#5 $
#
# Makefile for Poco ActiveMethod
#

include $(POCO_BASE)/build/rules/global

objects = ActiveMethod

target         = ActiveMethod
target_version = 1
target_libs    = PocoFoundation

include $(POCO_BASE)/build/rules/exec
