#
# Makefile
#
# Makefile for Poco SevenZip un7zip sample
#

include $(POCO_BASE)/build/rules/global

objects = un7zip

target         = un7zip
target_version = 1
target_libs    = PocoSevenZip PocoUtil PocoXML PocoJSON PocoFoundation

include $(POCO_BASE)/build/rules/exec
