#
# Makefile
#
# $Id: //poco/Main/template/TestSuite.make#3 $
#
# Makefile for Poco ExtJS testsuite
#

include $(POCO_BASE)/build/rules/global

objects = ExtJSTestSuite Driver \
	ExtJSTest

target         = testrunner
target_version = 1
target_libs    = PocoExtJS PocoWebWidgets PocoNet PocoXML PocoFoundation CppUnit

include $(POCO_BASE)/build/rules/exec
