#
# Makefile
#
# Makefile for Poco Encodings testsuite
#

include $(POCO_BASE)/build/rules/global

objects = EncodingsTestSuite Driver \
	DoubleByteEncodingTest

target         = testrunner
target_version = 1
target_libs    = PocoEncodings PocoFoundation CppUnit

include $(POCO_BASE)/build/rules/exec
