#
# Makefile
#
# $Id: //poco/Main/Foundation/samples/grep/Makefile#5 $
#
# Makefile for Poco grep
#

include $(POCO_BASE)/build/rules/global

objects = grep

target         = grep
target_version = 1
target_libs    = PocoFoundation

include $(POCO_BASE)/build/rules/exec
