#
# Makefile
#
# Makefile for Poco CodeGeneration testsuite
#

include $(POCO_BASE)/build/rules/global

objects = CodeGenerationTestSuite Driver \
	CodeGenerationTest

target         = testrunner
target_version = 1
target_libs    = PocoCodeGeneration PocoCppParser PocoFoundation CppUnit

include $(POCO_BASE)/build/rules/exec
