#
# Makefile
#
# $Id: //poco/Main/Net/samples/TimeServer/Makefile#2 $
#
# Makefile for Poco TimeServer
#

include $(POCO_BASE)/build/rules/global

objects = TimeServer

target         = TimeServer
target_version = 1
target_libs    = PocoUtil PocoNet PocoXML PocoFoundation

include $(POCO_BASE)/build/rules/exec
