#
# Makefile
#
# $Id: //poco/1.1.0/Net/samples/TimeServer/Makefile#1 $
#
# Makefile for Poco TimeServer
#

include $(POCO_BASE)/build/rules/global

objects = TimeServer

target         = TimeServer
target_version = 1
target_libs    = PocoFoundation PocoXML PocoNet PocoUtil

include $(POCO_BASE)/build/rules/exec
