# hunter_config(Foo VERSION ${HUNTER_Foo_VERSION} CMAKE_ARGS FOO_WITH_BOO=ON)

hunter_config(OpenSSL VERSION ${HUNTER_OpenSSL_VERSION} CMAKE_ARGS CMAKE_POSITION_INDEPENDENT_CODE=TRUE)
hunter_config(MySQL-client VERSION ${HUNTER_MySQL-client_VERSION} CMAKE_ARGS CMAKE_POSITION_INDEPENDENT_CODE=TRUE)
hunter_config(libpcre VERSION ${HUNTER_libpcre_VERSION} CMAKE_ARGS CMAKE_POSITION_INDEPENDENT_CODE=TRUE)
hunter_config(ZLIB VERSION ${HUNTER_ZLIB_VERSION} CMAKE_ARGS CMAKE_POSITION_INDEPENDENT_CODE=TRUE)
hunter_config(Expat VERSION ${HUNTER_Expat_VERSION} CMAKE_ARGS CMAKE_POSITION_INDEPENDENT_CODE=TRUE)
hunter_config(sqlite3 VERSION ${HUNTER_sqlite3_VERSION} CMAKE_ARGS CMAKE_POSITION_INDEPENDENT_CODE=TRUE)
