if (POCO_UNBUNDLED)
    find_package(ZLIB REQUIRED)
    set(SYSLIBS ${SYSLIBS} ${ZLIB_LIBRARIES})
    include_directories(${ZLIB_INCLUDE_DIRS})
endif (POCO_UNBUNDLED)
target_link_libraries(${BII_BLOCK_TARGET} INTERFACE ${SYSLIBS} )
