#
# Makefile
#
# Makefile for Poco TextConverter
#

include $(POCO_BASE)/build/rules/global

objects = TextConverter

target         = TextConverter
target_version = 1
target_libs    = PocoEncodings PocoFoundation

include $(POCO_BASE)/build/rules/exec
