#
# Makefile
#
# Makefile for Poco XSDTypes
#

include $(POCO_BASE)/build/rules/global

objects = \
	AbstractAttribute \
	AbstractAttributeGroup \
	AbstractElementImpl \
	AbstractGroup \
	AbstractList \
	All \
	AllIterator \
	AnnotatedObject \
	Annotation \
	AnnotationContent \
	Any \
	AnyAttribute \
	AnyIterator \
	AppInfo \
	Attribute \
	AttributeContent \
	AttributeGroup \
	AttributeGroupRef \
	AttributeHolder \
	AttributeRef \
	AttributeTypeRef \
	Binding \
	BindingProperties \
	Choice \
	ChoiceIterator \
	CollectionContent \
	ComplexType \
	Content \
	Definitions \
	Documentation \
	Element \
	ElementImpl \
	ElementIterator \
	ElementRef \
	ElementTypeRef \
	Group \
	GroupRef \
	InheritanceInfo \
	List \
	ListTypeRef \
	Message \
	NamespaceManager \
	Notation \
	Operation \
	Order \
	OrderContent \
	OrderIterator \
	OrderIteratorImpl \
	PortType \
	QName \
	Schema \
	Sequence \
	SequenceIterator \
	Service \
	SimpleRestriction \
	SimpleRestrictionInlineType \
	SimpleType \
	SimpleTypeInheritance \
	Type \
	TypesManager \
	Union \
	Visitable \
	Visitor \
	XSDException

target         = PocoXSDTypes
target_version = $(LIBVERSION)
target_libs    = PocoXML PocoFoundation

include $(POCO_BASE)/build/rules/lib
