#
# Makefile
#
# $Id: //poco/Main/template/TestSuite.make#3 $
#
# Makefile for Poco Web testsuite
#

include $(POCO_BASE)/build/rules/global

objects = Driver JSONTest SOAPTest WebTestSuite

target         = testrunner
target_version = 1
target_libs    = PocoWeb PocoFoundation CppUnit

include $(POCO_BASE)/build/rules/exec
