#
# Makefile
#
# Makefile for Poco download
#

include $(POCO_BASE)/build/rules/global

objects = download

target         = download
target_version = 1
target_libs    = PocoUtil PocoNet PocoXML PocoJSON PocoFoundation

include $(POCO_BASE)/build/rules/exec
