#
# Makefile
#
# $Id: //poco/Main/WebWidgets/samples/Makefile#2 $
#
# Makefile for Poco WebWidgets Samples
#

.PHONY: projects
clean all: projects
projects:
	$(MAKE) -C HTTPFormServer $(MAKECMDGOALS)

