#
# Makefile
#
# Makefile for Poco URI
#

include $(POCO_BASE)/build/rules/global

objects = URI

target         = URI
target_version = 1
target_libs    = PocoFoundation

include $(POCO_BASE)/build/rules/exec
