if(MSVC)
#	set(CMAKE_CXX_FLAGS_DEBUG_INIT          "/Zi /MD /WX- /0d /EHsc /Oy- /Ob1 /Oi /Ot /Oy /GS  /arch:SSE2 /fp:precise /RTC1 /D_DEBUG /D _WINDLL")
#	set(CMAKE_CXX_FLAGS_MINSIZEREL_INIT         "/MD /WX- /O1 /EHsc /Oy  /Ob1 /Oi /Ot /Oy /GS- /arch:SSE2 /fp:precise /D NDEBUG")
#	set(CMAKE_CXX_FLAGS_RELEASE_INIT            "/MD /WX- /O2 /EHsc /Oy  /Ob1 /Oi /Ot /Oy /GS- /arch:SSE2 /fp:precise /D NDEBUG")
#	set(CMAKE_CXX_FLAGS_RELWITHDEBINFO_INIT "/Zi /MD /Zi  /O2 /EHsc /Oy- /Ob1 /Oi /Ot /Oy /GS  /arch:SSE2 /fp:precise /RTC1 /D_DEBUG")
else()
#	set(CMAKE_CXX_FLAGS_DEBUG_INIT 			"-march=i686 -msse2 -msse3 -fPIC -m32 -O2 -fomit-frame-pointer")
#	set(CMAKE_CXX_FLAGS_MINSIZEREL_INIT       "-march=i686 -msse2 -msse3 -fPIC -m32 -O2 -fomit-frame-pointer")
#	set(CMAKE_CXX_FLAGS_RELEASE_INIT          "-march=i686 -msse2 -msse3 -fPIC -m32 -O2 -fomit-frame-pointer")
#	set(CMAKE_CXX_FLAGS_RELWITHDEBINFO_INIT   "-march=i686 -msse2 -msse3 -fPIC -m32 -O2 -fomit-frame-pointer")
endif()