#
# Makefile
#
# Makefile for Poco base64decode
#

include $(POCO_BASE)/build/rules/global

objects = base64decode

target         = base64decode
target_version = 1
target_libs    = PocoFoundation

include $(POCO_BASE)/build/rules/exec
