#
# Makefile
#
# $Id: //poco/Main/Foundation/samples/deflate/Makefile#5 $
#
# Makefile for Poco deflate
#

include $(POCO_BASE)/build/rules/global

objects = deflate

target         = deflate
target_version = 1
target_libs    = PocoFoundation

include $(POCO_BASE)/build/rules/exec
