#
# Makefile
#
# $Id: //poco/Main/template/sample.make#4 $
#
# Makefile for Poco PocoDoc
#

include $(POCO_BASE)/build/rules/global

objects = DocWriter PocoDoc

target         = PocoDoc
target_version = 1
target_libs    = PocoCppParser PocoFoundation PocoXML PocoUtil

include $(POCO_BASE)/build/rules/exec
