#
# Makefile
#
# Makefile for Poco SQLite testsuite
#

include $(POCO_BASE)/build/rules/global

objects = SQLiteTestSuite Driver \
	SQLiteTest

target         = testrunner
target_version = 1
target_libs    = PocoSQLSQLite PocoSQL PocoFoundation PocoCppUnit

include $(POCO_BASE)/build/rules/exec
