#
# Makefile
#
# $Id: //poco/1.7/DNSSD/Bonjour/Makefile#1 $
#
# Makefile for Poco DNSSD Bonjour
#

include $(POCO_BASE)/build/rules/global

objects = \
	BonjourBrowserImpl BonjourResponderImpl EventLoop

target         = PocoDNSSDBonjour
target_version = 1
target_libs    = PocoNet PocoDNSSD PocoFoundation

include $(POCO_BASE)/build/rules/lib
