#
# Makefile
#
# $Id: //poco/Main/Foundation/samples/StringTokenizer/Makefile#5 $
#
# Makefile for Poco StringTokenizer
#

include $(POCO_BASE)/build/rules/global

objects = StringTokenizer

target         = StringTokenizer
target_version = 1
target_libs    = PocoFoundation

include $(POCO_BASE)/build/rules/exec
