#
# Makefile
#
# $Id: //poco/1.4/Zip/Makefile#1 $
#
# Makefile for Poco SevenZip
#

include $(POCO_BASE)/build/rules/global

objects = \
	Archive \
	ArchiveEntry \
	7zAlloc \
	7zBuf \
	7zBuf2 \
	7zCrc \
	7zCrcOpt \
	7zDec \
	7zFile \
	7zIn \
	7zStream \
	Bcj2 \
	Bra \
	Bra86 \
	CpuArch \
	Lzma2Dec \
	LzmaDec \
	Ppmd7 \
	Ppmd7Dec

target         = PocoSevenZip
target_version = $(LIBVERSION)
target_libs    = PocoFoundation

include $(POCO_BASE)/build/rules/lib
